stages:          # List of stages for jobs, and their order of execution
  - test

unit-test-job:   # This job runs in the test stage.
  image: node:latest


  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - export MONGODB_URI='mongodb://localhost:27017/polytech?readPreference=primary&ssl=false'
    - npm i
    - npm i -D typescript
    - npm run build --if-present
    - npm run test