# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MONGODB_URI: "mongodb://ci:aReallySecuredPassword@localhost:27017/polycode?authSource=admin&serverSelectionTimeoutMS=2000&ssl=false"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        mongodb-version: ['4.2', '4.4', '5.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Start mongodb
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: ci
        mongodb-password: aReallySecuredPassword
        mongodb-db: polycode
  

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm i -D typescript
    - run: npm run build --if-present
    - run: npm test

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: start ssh-agent
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH }}

    - name: send code 
      run: |
        git add -A
        git commit -m "release"
        git remote add origin git@ec2-13-37-32-140.eu-west-3.compute.amazonaws.com:/www
        git push origin master